import Vue from 'vue';
import Vuex from 'vuex';


Vue.use(Vuex);

let store = new Vuex.Store({
  state: {
    CesiumChange: true,
    StyleMeum: [false],
    StyleChange: true,
    NowLayerIndex: 1,
    StyleBarChange: true,
    AddViewSign: false,
    NowViewIndex: 1,
    ViewChange: true,
    ServiceList: [
      "WMS",
      "WMTS",
      "TMS",
      "WFS",
      "OpenStreetMap",
      "ArcGIS",
      "LOCAL",
    ],
    icon: [
      {
        name: "叉",
        path: "data/icons/叉_64.png"
      },
      {
        name: "倒三角",
        path: "data/icons/倒三角_64.png"
      },
      {
        name: "三角形",
        path: "data/icons/三角形_64.png"
      },
      {
        name: "五边形",
        path: "data/icons/五边形_64.png"
      },
      {
        name: "五角星",
        path: "data/icons/五角星_64.png"
      },
      {
        name: "圆环",
        path: "data/icons/圆环_64.png"
      },
      {
        name: "圆心_64",
        path: "data/icons/圆心_64.png"
      },
      {
        name: "圆形",
        path: "data/icons/圆形_64.png"
      },
      {
        name: "正方形",
        path: "data/icons/正方形_64.png"
      },
      {
        name: "嘉然",
        path: "data/icons/嘉然.png"
      },
    ],
    layers: [
      {
        name: "hangzhou_wms",
        layer: "GIS_lab_3:hangzhou_img",
        type: "TIFF",
        format: "image/png",
        service: "WMS",
        time: "2022-3-30",
        url: "http://localhost:8080/geoserver/GIS_lab_3/wms",
        show: false,
        color: "#ff0000",
        StyleBarChange: true,
        style: "",
        transparency: 0,
        size: 1,
        propertyNames: [],
        LabelShow: false,
        LabelProperty: 0,
        OutLineWidth: 1,
        OutLineColor: "#ff0000",
        OutLineTransparency: 0,
        IconShow: false,
        IconIndex: 0,
        IconWidth: 20,
        IconHeight: 20,
        IconRotation: 0,
        IconTransparency: 0,
        IconColor: "#ff0000",
        EntityLat: 0,
        EntityLon: 0,
        EntityAl: 0,
        EntityLon: 0,
        EntityPitch: 0,
        EntityHpr: 0,
        ModelColorSet: [
          "#ff0000",
          "#00ff00",
          "#0000ff",
        ],
        ModelSplitHeightSet: [
          50,
        ],
      },
      {
        name: "hangzhou_wmts",
        layer: "GIS_lab_3:hangzhou",
        type: "SHP",
        format: "image/png",
        service: "WMTS",
        time: "2022-3-30",
        url: "http://localhost:8080/geoserver/gwc/service/wmts/rest/GIS_lab_3:hangzhou/{style}/{TileMatrixSet}/{TileMatrixSet}:{TileMatrix}/{TileRow}/{TileCol}?format=image/png",
        show: false,
        color: "#ff0000",
        style: "",
        transparency: 0,
        size: 1,
        propertyNames: [],
        LabelShow: false,
        LabelProperty: 0,
        OutLineWidth: 1,
        OutLineColor: "#ff0000",
        OutLineTransparency: 0,
        IconShow: false,
        IconIndex: 0,
        IconWidth: 20,
        IconHeight: 20,
        IconRotation: 0,
        IconTransparency: 0,
        IconColor: "#ff0000",
        EntityLat: 0,
        EntityLon: 0,
        EntityAl: 0,
        EntityLon: 0,
        EntityPitch: 0,
        EntityHpr: 0,
        ModelColorSet: [
          "#ff0000",
          "#00ff00",
          "#0000ff",
        ],
        ModelSplitHeightSet: [
          50,
        ],
      },
      {
        name: "hangzhou_tms",
        layer: "GIS_lab_3:hangzhou",
        type: "SHP",
        format: "image/png",
        service: "TMS",
        time: "2022-3-30",
        url: "http://localhost:8080/geoserver/gwc/service/tms/1.0.0/GIS_lab_3%3Ahangzhou@EPSG%3A900913@png/{z}/{x}/{reverseY}.png",
        show: false,
        color: "#ff0000",
        style: "",
        transparency: 0,
        size: 1,
        propertyNames: [],
        LabelShow: false,
        LabelProperty: 0,
        OutLineWidth: 1,
        OutLineColor: "#ff0000",
        OutLineTransparency: 0,
        IconShow: false,
        IconIndex: 0,
        IconWidth: 20,
        IconHeight: 20,
        IconRotation: 0,
        IconTransparency: 0,
        IconColor: "#ff0000",
        EntityLat: 0,
        EntityLon: 0,
        EntityAl: 0,
        EntityLon: 0,
        EntityPitch: 0,
        EntityHpr: 0,
        ModelColorSet: [
          "#ff0000",
          "#00ff00",
          "#0000ff",
        ],
        ModelSplitHeightSet: [
          50,
        ],
      },
      {
        name: "hangzhou_wfs",
        layer: "GIS_lab_3:hangzhou",
        type: "GeoJson",
        format: "polygon",
        service: "WFS",
        time: "2022-3-30",
        url: "http://localhost:8080/geoserver/GIS_lab_3/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=GIS_lab_3%3Ahangzhou&maxFeatures=500000&outputFormat=application%2Fjson",
        style: "",
        show: false,
        color: "#ff0000",
        transparency: 0,
        size: 1,
        propertyNames: [],
        LabelShow: false,
        LabelProperty: 0,
        OutLineWidth: 1,
        OutLineColor: "#ff0000",
        OutLineTransparency: 0,
        IconShow: false,
        IconIndex: 0,
        IconWidth: 20,
        IconHeight: 20,
        IconRotation: 0,
        IconTransparency: 0,
        IconColor: "#ff0000",
        EntityLat: 0,
        EntityLon: 0,
        EntityAl: 0,
        EntityLon: 0,
        EntityPitch: 0,
        EntityHpr: 0,
        ModelColorSet: [
          "#ff0000",
          "#00ff00",
          "#0000ff",
        ],
        ModelSplitHeightSet: [
          50,
        ],
      },
      {
        name: "OpenStreetMap",
        layer: "OpenStreetMap",
        type: "MAP",
        format: "tile",
        service: "OpenStreetMap",
        time: "2022-3-30",
        url: "https://tile-{s}.openstreetmap.fr/hot/{z}/{x}/{y}.png",
        style: "",
        show: false,
        color: "#ff0000",
        transparency: 0,
        size: 1,
        propertyNames: [],
        LabelShow: false,
        LabelProperty: 0,
        OutLineWidth: 1,
        OutLineColor: "#ff0000",
        OutLineTransparency: 0,
        IconShow: false,
        IconIndex: 0,
        IconWidth: 20,
        IconHeight: 20,
        IconRotation: 0,
        IconTransparency: 0,
        IconColor: "#ff0000",
        EntityLat: 0,
        EntityLon: 0,
        EntityAl: 0,
        EntityLon: 0,
        EntityPitch: 0,
        EntityHpr: 0,
        ModelColorSet: [
          "#ff0000",
          "#00ff00",
          "#0000ff",
        ],
        ModelSplitHeightSet: [
          50,
        ],
      },
      {
        name: "OpenStreetMap_black",
        layer: "OpenStreetMap_black",
        type: "MAP",
        format: "tile",
        service: "OpenStreetMap",
        time: "2022-3-30",
        url: "https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png",
        style: "",
        show: false,
        color: "#ff0000",
        transparency: 0,
        size: 1,
        propertyNames: [],
        LabelShow: false,
        LabelProperty: 0,
        OutLineWidth: 1,
        OutLineColor: "#ff0000",
        OutLineTransparency: 0,
        IconShow: false,
        IconIndex: 0,
        IconWidth: 20,
        IconHeight: 20,
        IconRotation: 0,
        IconTransparency: 0,
        IconColor: "#ff0000",
        EntityLat: 0,
        EntityLon: 0,
        EntityAl: 0,
        EntityLon: 0,
        EntityPitch: 0,
        EntityHpr: 0,
        ModelColorSet: [
          "#ff0000",
          "#00ff00",
          "#0000ff",
        ],
        ModelSplitHeightSet: [
          50,
        ],
      },
      {
        name: "ArcGIS_Satellite",
        layer: "ArcGIS_Satellite",
        type: "MAP",
        format: "tile",
        service: "ArcGIS",
        time: "2022-3-30",
        url: "https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer",
        style: "",
        show: false,
        color: "#ff0000",
        transparency: 0,
        size: 1,
        propertyNames: [],
        LabelShow: false,
        LabelProperty: 0,
        OutLineWidth: 1,
        OutLineColor: "#ff0000",
        OutLineTransparency: 0,
        IconShow: false,
        IconIndex: 0,
        IconWidth: 20,
        IconHeight: 20,
        IconRotation: 0,
        IconTransparency: 0,
        IconColor: "#ff0000",
        EntityLat: 0,
        EntityLon: 0,
        EntityAl: 0,
        EntityLon: 0,
        EntityPitch: 0,
        EntityHpr: 0,
        ModelColorSet: [
          "#ff0000",
          "#00ff00",
          "#0000ff",
        ],
        ModelSplitHeightSet: [
          50,
        ],
      },
      {
        name: "ArcGIS_Street",
        layer: "ArcGIS_Street",
        type: "MAP",
        format: "tile",
        service: "ArcGIS",
        time: "2022-3-30",
        url: "http://services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer",
        style: "",
        show: false,
        color: "#ff0000",
        transparency: 0,
        size: 1,
        propertyNames: [],
        LabelShow: false,
        LabelProperty: 0,
        OutLineWidth: 1,
        OutLineColor: "#ff0000",
        OutLineTransparency: 0,
        IconShow: false,
        IconIndex: 0,
        IconWidth: 20,
        IconHeight: 20,
        IconRotation: 0,
        IconTransparency: 0,
        IconColor: "#ff0000",
        EntityLat: 0,
        EntityLon: 0,
        EntityAl: 0,
        EntityLon: 0,
        EntityPitch: 0,
        EntityHpr: 0,
        ModelColorSet: [
          "#ff0000",
          "#00ff00",
          "#0000ff",
        ],
        ModelSplitHeightSet: [
          50,
        ],
      },
      {
        name: "黄东海温盐深",
        layer: "黄东海温盐深.geojson",
        type: "GeoJson",
        format: "point",
        service: "LOCAL",
        time: "2022-4-6",
        url: "黄东海温盐深.geojson",
        style: "",
        show: false,
        color: "#ff0000",
        transparency: 0,
        size: 1,
        propertyNames: [],
        LabelShow: false,
        LabelProperty: 0,
        OutLineWidth: 1,
        OutLineColor: "#ff0000",
        OutLineTransparency: 0,
        IconShow: false,
        IconIndex: 0,
        IconWidth: 20,
        IconHeight: 20,
        IconRotation: 0,
        IconTransparency: 0,
        IconColor: "#ff0000",
        EntityLat: 0,
        EntityLon: 0,
        EntityAl: 0,
        EntityLon: 0,
        EntityPitch: 0,
        EntityHpr: 0,
        ModelColorSet: [
          "#ff0000",
          "#00ff00",
          "#0000ff",
        ],
        ModelSplitHeightSet: [
          50,
        ],
      },
      {
        name: "chla",
        layer: "chla.geojson",
        type: "GeoJson",
        format: "point",
        service: "LOCAL",
        time: "2022-4-6",
        url: "chla.geojson",
        style: "",
        show: false,
        color: "#ff0000",
        transparency: 0,
        size: 1,
        propertyNames: [],
        LabelShow: false,
        LabelProperty: 0,
        OutLineWidth: 1,
        OutLineColor: "#ff0000",
        OutLineTransparency: 0,
        IconShow: false,
        IconIndex: 0,
        IconWidth: 20,
        IconHeight: 20,
        IconRotation: 0,
        IconTransparency: 0,
        IconColor: "#ff0000",
        EntityLat: 0,
        EntityLon: 0,
        EntityAl: 0,
        EntityLon: 0,
        EntityPitch: 0,
        EntityHpr: 0,
        ModelColorSet: [
          "#ff0000",
          "#00ff00",
          "#0000ff",
        ],
        ModelSplitHeightSet: [
          50,
        ],
      },
      {
        name: "Wood_Tower",
        layer: "Wood_Tower.glb",
        type: "GLTF",
        format: "Model",
        service: "LOCAL",
        time: "2022-4-7",
        url: "Wood_Tower.glb",
        style: "",
        show: false,
        color: "#ff0000",
        transparency: 0,
        size: 1,
        propertyNames: [],
        LabelShow: false,
        LabelProperty: 0,
        OutLineWidth: 1,
        OutLineColor: "#ff0000",
        OutLineTransparency: 0,
        IconShow: false,
        IconIndex: 0,
        IconWidth: 20,
        IconHeight: 20,
        IconRotation: 0,
        IconTransparency: 0,
        IconColor: "#ff0000",
        EntityLat: 0,
        EntityLon: 0,
        EntityAl: 0,
        EntityRoll: 0,
        EntityPitch: 0,
        EntityHeading: 0,
        ModelColorSet: [
          "#ff0000",
          "#00ff00",
          "#0000ff",
        ],
        ModelSplitHeightSet: [
          50,
        ],
      },
      {
        name: "Tileset",
        layer: "Tileset.json",
        type: "3DTile",
        format: "Model",
        service: "LOCAL",
        time: "2022-4-7",
        url: "Tileset/Tileset.json",
        style: "",
        show: false,
        color: "#000000",
        transparency: 0,
        size: 1,
        propertyNames: [],
        LabelShow: false,
        LabelProperty: 0,
        OutLineWidth: 1,
        OutLineColor: "#ff0000",
        OutLineTransparency: 0,
        IconShow: false,
        IconIndex: 0,
        IconWidth: 20,
        IconHeight: 20,
        IconRotation: 0,
        IconTransparency: 0,
        IconColor: "#ff0000",
        EntityLat: 0,
        EntityLon: 0,
        EntityAl: 0,
        EntityRoll: 0,
        EntityPitch: 0,
        EntityHeading: 0,
        ModelColorSet: [
          "#ff0000",
          "#00ff00",
          "#0000ff",
        ],
        ModelSplitHeightSet: [
          50,
        ],
      },
      {
        name: "us_states",
        layer: "ne_10m_us_states.topojson",
        type: "TopoJson",
        format: "polygon",
        service: "LOCAL",
        time: "2022-4-16",
        url: "ne_10m_us_states.topojson",
        style: "",
        show: false,
        color: "#000000",
        transparency: 0,
        size: 1,
        propertyNames: [],
        LabelShow: false,
        LabelProperty: 0,
        OutLineWidth: 1,
        OutLineColor: "#ff0000",
        OutLineTransparency: 0,
        IconShow: false,
        IconIndex: 0,
        IconWidth: 20,
        IconHeight: 20,
        IconRotation: 0,
        IconTransparency: 0,
        IconColor: "#ff0000",
        EntityLat: 0,
        EntityLon: 0,
        EntityAl: 0,
        EntityRoll: 0,
        EntityPitch: 0,
        EntityHeading: 0,
        ModelColorSet: [
          "#ff0000",
          "#00ff00",
          "#0000ff",
        ],
        ModelSplitHeightSet: [
          50,
        ],
      },
    ],
    views: [
      {
        name: "",
        Lat: 15,
        Lon: 110,
        Alt: 20000,
        Roll: 0,
        Pitch: -90,
        Heading: 0,
        layer: undefined,
      },
    ],
    conditions: [
      {
        sum_of_human: 2000,
        incubation_period: 4,
        treat_willingness: 4,
        isolation_pos: 400,
        infection_area: 0.05,
        move_area_param: 0.7,
        first_infected_cnt: 20,
        total_day: 100,
        infected_index_history: [],
        haveComp: false,
        x1: [],
        x2: [],
        y1: [],
        y2: [],
        plt_xSet: [],
        plt_ySet: [],
        plt_x_infectionSet: [],
        plt_y_infectionSet: [],
        plt_x_sickSet: [],
        plt_y_sickSet: [],
        plt_x_isolationSet: [],
        plt_y_isolationSet: [],
        west: null,
        east: null,
        north: null,
        south: null,
        day: 0,
        isolation_set:null,
        infected_index_set:null
      }
    ],
    peopleStyle: {
      color: "#ffffff",
      transparency: 0,
      size: 5,
      OutLineWidth: 1,
      OutLineColor: "#000000",
      OutLineTransparency: 0,
      IconShow: false,
      IconIndex: 0,
      IconWidth: 20,
      IconHeight: 20,
      IconRotation: 0,
      IconTransparency: 0,
      IconColor: "#ffffff",
    },
    injectionStyle: {
      color: "#00ff00",
      transparency: 0,
      size: 10,
      OutLineWidth: 1,
      OutLineColor: "#000000",
      OutLineTransparency: 0,
      IconShow: false,
      IconIndex: 0,
      IconWidth: 20,
      IconHeight: 20,
      IconRotation: 0,
      IconTransparency: 0,
      IconColor: "#ffffff",
      spread:false
    },
    sickStyle: {
      color: "#ff0000",
      transparency: 0,
      size: 10,
      OutLineWidth: 1,
      OutLineColor: "#000000",
      OutLineTransparency: 0,
      IconShow: false,
      IconIndex: 0,
      IconWidth: 20,
      IconHeight: 20,
      IconRotation: 0,
      IconTransparency: 0,
      IconColor: "#ffffff",
      spread:false
    },
    isolationStyle: {
      color: "#0000ff",
      transparency: 0,
      size: 10,
      OutLineWidth: 1,
      OutLineColor: "#000000",
      OutLineTransparency: 0,
      IconShow: false,
      IconIndex: 0,
      IconWidth: 20,
      IconHeight: 20,
      IconRotation: 0,
      IconTransparency: 0,
      IconColor: "#ffffff",
    },
    conditionSelectSign:false
  },
  getters: {
    getlayer(state) {
      return state.layers;
    }
  },
  mutations: {
    SituationChange(state, change) {
      state.CesiumChange = change;
    },
    UpdateLayersToStore(state, layer) {
      state.layers = layer;
    },
    AddLayersToStore(state, layer) {
      state.layers.push(layer);
    },
    StyleChangeSubmit(state, change) {
      state.StyleChange = change;

    },
    StyleMeumSubmit(state, Style) {
      state.StyleMeum = Style;
    },
    NowLayerIndexSubmit(state, index) {
      state.NowLayerIndex = index;
    },
    StyleBarChangeSubmit(state, change) {
      state.StyleBarChange = change;
    },
    AddViewSignSubmit(state, change) {
      state.AddViewSign = change
    },
    AddView(state, view) {
      state.views.push(view);
    },
    AddCondition(state, condition) {
      state.conditions.push(condition);
    },
    NowViewIndexSubmit(state, index) {
      state.NowViewIndex = index;
    },
    ViewChangeSubmit(state, change) {
      state.ViewChange = change;
    }
  },
  actions: {}
})

export default store;